version: '3.3'

services:
  mssql:
    container_name: compas-sitipe-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    cap_add:
      - SYS_PTRACE
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1434:1433"
